# Stage 1: Build
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build
# Stage 2: Nginx
FROM nginx:1.27-alpine

# Actualizar paquetes del sistema
RUN apk update && \
    apk upgrade --no-cache && \
    rm -rf /var/cache/apk/*

# Instalar gettext
RUN apk add --no-cache gettext

# React build files
COPY --from=build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY public/env.template.js /usr/share/nginx/html/env.template.js
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

EXPOSE 3000
ENTRYPOINT ["/docker-entrypoint.sh"]