# Activar logging debug
error_log /dev/stderr debug;
access_log /dev/stdout;

server {
    listen 3000;
    server_name _;

    root /usr/share/nginx/html;

    # Habilitar gzip
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 256;

    # SPA fallback para todas las rutas de React
    location = /env.js {
        deny all;
        return 404;
    }
    location = /env.template.js {
        deny all;
        return 404;
    }
    location = /health.json {
        access_log off;       
        log_not_found off;
        return 200 '{"status":"ok"}';
        add_header Content-Type application/json;
    }
    location / {
        try_files $uri /index.html;
    }

    # Proxy opcional hacia backend
    # location /api/ {
    #     proxy_pass http://TU_BACKEND:4000/;
    #     proxy_http_version 1.1;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection 'upgrade';
    #     proxy_set_header Host $host;
    #     proxy_cache_bypass $http_upgrade;
    # }

    # Evitar cache de index.html
    location = /index.html {
        add_header Cache-Control "no-cache";
    }
 

    # Configuración de errores comunes
    error_page 404 /index.html;
}
