FROM node:25.3-alpine AS builder

RUN apk update && \
    apk upgrade --no-cache && \
    rm -rf /var/cache/apk/*

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .

# Imagen final
FROM node:25.3-alpine

RUN apk update && \
    apk upgrade --no-cache && \
    apk add --no-cache zlib>=1.3.2-r0 && \
    rm -rf /var/cache/apk/*

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/src ./src

# Elimina npm bundled — aquí viven tar, minimatch, glob, diff vulnerables
RUN rm -rf /usr/local/lib/node_modules/npm && \
    rm -rf /usr/local/include/node

RUN chown -R node:node /app
USER node

EXPOSE 4000

CMD ["node", "src/index.js"]